// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrcaStarsWebApplication.Models;

namespace OrcaStarsWebApplication.Migrations
{
    [DbContext(typeof(BitDataContext))]
    partial class BitDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OrcaStarsWebApplication.Models.Business", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("BusinessContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Hours")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Social")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoreFront")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessContactId");

                    b.ToTable("Businesses");
                });

            modelBuilder.Entity("OrcaStarsWebApplication.Models.BusinessContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("OrcaStarsWebApplication.Models.Hours", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FriC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FriO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MonC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MonO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SatC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SatO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SunC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SunO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThursC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThursO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TuesC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TuesO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WedC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WedO")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Hours");
                });

            modelBuilder.Entity("OrcaStarsWebApplication.Models.SocialMedia", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Facebook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instagram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Twitter")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("SocialMedias");
                });

            modelBuilder.Entity("OrcaStarsWebApplication.Models.Business", b =>
                {
                    b.HasOne("OrcaStarsWebApplication.Models.BusinessContact", null)
                        .WithMany("Businesses")
                        .HasForeignKey("BusinessContactId");
                });
#pragma warning restore 612, 618
        }
    }
}
